### ISSUE TITLE
关于ALI-BRANDLIFT数据的问题

### ISSUE THREAD

**Issue by zytang18** [aifor/eeuen#2]
您好，我对ALI-BRANDLIFT Dataset中的treatment detail有疑问。exposed是如何定义的呢（或如何与unexposed区别开的呢）？请问在其中exposed和click有什么区别呢？另外，如何把其中的click和outcome中的revisit taobao作区分呢？
感谢！

**Comment by Trangle** [comment]
您好，邮件已收到。

**Comment by Trangle** [comment]
是否曝光的工业含义可以参考原论文中的描述，应该有具体的介绍。数据收集自业务的某几个具体场景，这里click并不仅仅限定在当前场景下的brand点击行为，可以看做转化的一种，因此没有在A场景曝光的品牌也可以有其他渠道被触达后发生后续的点击行为。

**Comment by zytang18** [comment]
谢谢您的解答。是否可以理解为click不需要被分到treatment group也可以发生呢？我的疑惑是，如果用户发生了click的行为，可能在这一次click就已经完成了购买，因此会降低我们关心的revisit（conversion target）的可能性。

**Comment by Trangle** [comment]
是的。这里不关心具体是哪次click引起的购买行为，数据集构成和问题不是倾向于这种规则的定义归因，可以好好理解下。
