### ISSUE TITLE
关于ali brand uplift数据

### ISSUE THREAD

**Issue by zytang18** [aifor/eeuen#3]
请问uplift_data.zip和uplift_data_v2.zip有什么区别呢？

**Comment by Trangle** [comment]
v2修正了分隔符，使用v2即可

**Comment by zytang18** [comment]
您好，所有的用户和广告特征都经过离散化处理。请问其顺序是否还有意义呢？这些离散的特征是ordinal的还是nominal的呢？

**Comment by Trangle** [comment]
您好，邮件已收到。

**Comment by Trangle** [comment]
> 您好，所有的用户和广告特征都经过离散化处理。请问其顺序是否还有意义呢？这些离散的特征是ordinal的还是nominal的呢？

由于保密要求，这里离散化的方式不便于公开，所有特征当做独立的单值对待，不承诺具有原始的单调含义
